"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%^@5%ui$7qda5r*^u_@++r=@zfmjtw(f0)5n+)2tii+m+d!046'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ==============================================================================
# REAL-WORLD ANALOGY: The App Store Registry
# ------------------------------------------------------------------------------
# Imagine you bought a brand new, high-tech smartphone (our Django framework).
# By default, the smartphone comes with pre-installed stock apps (like the admin dashboard,
# auth manager, session keeper, and static file loaders).
# 
# However, when you write custom applications for this phone (like our 'accounts' app
# or our new 'feed' app), the phone's operating system has absolutely no idea they exist!
# They are just folders sitting in memory.
# 
# Listing 'feed' inside INSTALLED_APPS is like registering our newly developed application
# in the phone's official App Store Registry. Once registered, Django's operating system
# can boot the app up, load its models, read its configurations, and make it fully functional!
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts', # Our custom user authentication and profile app
    'feed', # Our custom social feed app for posting whispers and managing comments
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ==============================================================================
# REAL-WORLD ANALOGY: Updating the Security Guard's Manual
# ------------------------------------------------------------------------------
# Imagine the Django settings file is the master blueprint and manual for your entire
# web application's building. By default, the blueprint tells the building's
# security guard (Django's auth engine) to use the standard factory-issue keys
# (the default auth.User model) to unlock doors.
# 
# Now that we have crafted custom keys (our new User model inside the 'accounts' app),
# the security guard will completely ignore them and still ask for the factory-issue keys
# unless we explicitly update the security manual.
# 
# Adding AUTH_USER_MODEL is like crossing out the old instructions in the security manual
# and writing in bold letters: "ATTENTION: From now on, use the custom 'accounts.User' 
# model as the official key card template for everyone in the building!"
# ==============================================================================

# We tell Django to use our custom User model instead of the default built-in User model.
# The format is 'app_name.ModelName', which in our case is 'accounts.User'.
# This must be defined before running migrations for the first time, otherwise
# Django will set up database tables using the old default model and cause major conflicts later.
AUTH_USER_MODEL = 'accounts.User'

# ==============================================================================
# REAL-WORLD ANALOGY: The Bouncer's Redirection Instructions
# ------------------------------------------------------------------------------
# Imagine you try to walk straight past the bouncer into the club's VIP Private Lounge
# (the protected Dashboard) without a valid visitor session pass.
# 
# The bouncer stops you. But instead of just throwing you into the street and locking the
# door (which would leave the visitor confused!), the bouncer needs to know where to direct you.
# 
# Defining LOGIN_URL is like giving the bouncer a clear instruction manual:
# "When you kick an unauthenticated visitor out of a protected room, politely walk them
# over to the Login registration gate (our view path named 'login') so they can sign in!"
# ==============================================================================

# We tell Django where to redirect unauthenticated users when they try to access a protected view.
# By passing the URL name 'login', Django will look up the path mapped to name='login' in our URLs.
LOGIN_URL = 'login'

